window "resizable" false
window "dimensions" 300 300

mainloop:
pen "size" 5
colour #fff

loc 999 999 (second * 6).sin() * 70 (second * 6).cos() * 70
pen "down"
goto 0 0
pen "size" 8
loc 999 999 (minute * 6).sin() * 50 (minute * 6).cos() * 50
pen "up"

goto 0 0
pen "down"
h = hour * 30 + (minute / 2)
goto h.sin() * 20 h.cos() * 20
pen "up"

count = 0
loop 12 (
  count += 30
  goto count.sin() * 100 count.cos() * 100
  text count / 30 6
)
import "win-buttons"
